# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 594eeebb83b8e054d8f97ccf7400780b5424ca9d36c91b970b9c2f34894c4282e72748048858e94304e638cee24ce961b88bf6fe3c39720cc40b9c8effa4a692

test:
  secret_key_base: 1b774faa3f905f66816d36cde2350f1c2ed2d769efe48271b34ef5f548b475025227eeba2f94b0e23c082b565ebc14905a1eadbdd3bba3712687c9946b1122bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
